---@class CS.LuaBehaviour
---@field CacheCoroutines Dictionary`2
---@field LoadedCache List`1
---@field BindEvent fun(self:CS.LuaBehaviour,eventId:int32, id:int32, callBack:LuaFunction)
---@field GetChild fun(self:CS.LuaBehaviour,id:int32, root:CS.LuaBehaviour):Object
---@field GetText fun(self:CS.LuaBehaviour,id:int32):string
---@field IsActive fun(self:CS.LuaBehaviour,id:int32):boolean
---@field IsEnable fun(self:CS.LuaBehaviour,id:int32):boolean
---@field IsInteractable fun(self:CS.LuaBehaviour,id:int32):boolean
---@field SetActive fun(self:CS.LuaBehaviour,id:int32, active:boolean)
---@field SetAnchoredPosition fun(self:CS.LuaBehaviour,id:int32, x:single, y:single, z:single)
---@field SetButtonEnable fun(self:CS.LuaBehaviour,id:int32, enabled:boolean)
---@field SetCanvasGroupAlpha fun(self:CS.LuaBehaviour,id:int32, alpha:single)
---@field SetEnable fun(self:CS.LuaBehaviour,id:int32, enabled:boolean)
---@field SetFontSize fun(self:CS.LuaBehaviour,id:int32, size:int32)
---@field SetImage fun(self:CS.LuaBehaviour,id:int32, dir:string, spriteName:string, resetSize:boolean, sizeRatio:single)
---@field SetInteractable fun(self:CS.LuaBehaviour,id:int32, interactable:boolean)
---@field SetParent fun(self:CS.LuaBehaviour,id1:int32, id2:int32, worldPositionStays:boolean)
---@field SetPosition fun(self:CS.LuaBehaviour,id:int32, x:single, y:single, z:single)
---@field SetRotation fun(self:CS.LuaBehaviour,id:int32, x:single, y:single, z:single)
---@field SetScale fun(self:CS.LuaBehaviour,id:int32, x:single, y:single, z:single)
---@field SetSliderValue fun(self:CS.LuaBehaviour,id:int32, value:single)
---@field SetText fun(self:CS.LuaBehaviour,id:int32, text:string)

---@class CS.LuaUtil
---@field ClearDontDestroyObjs fun()
---@field ClearUICache fun()
---@field CreateWindow fun(parentId:int32, path:string, layer:int32, args:LuaTable, callback:LuaFunction):int32
---@field DestroyWindow fun(id:int32, destroy:boolean)
---@field DontDestroyOnLoad fun(obj:Object, isDontDestroy:boolean)
---@field IsNull fun(obj:Object):boolean
---@field LoadScene fun(scene:string, callback:LuaFunction)
---@field Patching fun(url:string, o:Object, callback:LuaFunction)
---@field SetSelfPlayerId fun(id:int32)

