// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// Export file: exported/behaviac_generated/behaviors/generated_behaviors.cs
// ---------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;

namespace behaviac
{
	// Source file: FirstTree

	[behaviac.GeneratedTypeMetaInfo()]
	class Condition_bt_FirstTree_node2 : behaviac.Condition
	{
		public Condition_bt_FirstTree_node2()
		{
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			int opl = ((FirstAgent)pAgent).intValue;
			int opr = 500;
			bool op = opl >= opr;
			return op ? EBTStatus.BT_SUCCESS : EBTStatus.BT_FAILURE;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_FirstTree_node3 : behaviac.Action
	{
		public Action_bt_FirstTree_node3()
		{
			this.m_resultOption = EBTStatus.BT_SUCCESS;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			((FirstAgent)pAgent).OnOver();
			return EBTStatus.BT_SUCCESS;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Parallel_bt_FirstTree_node4 : behaviac.Parallel
	{
		public Parallel_bt_FirstTree_node4()
		{
			m_failPolicy = behaviac.FAILURE_POLICY.FAIL_ON_ONE;
			m_succeedPolicy = behaviac.SUCCESS_POLICY.SUCCEED_ON_ALL;
			m_exitPolicy = behaviac.EXIT_POLICY.EXIT_ABORT_RUNNINGSIBLINGS;
			m_childFinishPolicy = behaviac.CHILDFINISH_POLICY.CHILDFINISH_LOOP;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Compute_bt_FirstTree_node5 : behaviac.Compute
	{
		public Compute_bt_FirstTree_node5()
		{
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			EBTStatus result = EBTStatus.BT_SUCCESS;
			int opr1 = ((FirstAgent)pAgent).intValue;
			int opr2 = 1;
			((FirstAgent)pAgent).intValue = (int)(opr1 + opr2);
			return result;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_FirstTree_node6 : behaviac.Action
	{
		public Action_bt_FirstTree_node6()
		{
			this.m_resultOption = EBTStatus.BT_SUCCESS;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			((FirstAgent)pAgent).OnMethod();
			return EBTStatus.BT_SUCCESS;
		}
	}

	public static class bt_FirstTree
	{
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("FirstTree");
			bt.IsFSM = false;
#if !BEHAVIAC_RELEASE
			bt.SetAgentType("FirstAgent");
#endif
			// children
			{
				Sequence node0 = new Sequence();
				node0.SetClassNameString("Sequence");
				node0.SetId(0);
#if !BEHAVIAC_RELEASE
				node0.SetAgentType("FirstAgent");
#endif
				bt.AddChild(node0);
				{
					IfElse node1 = new IfElse();
					node1.SetClassNameString("IfElse");
					node1.SetId(1);
#if !BEHAVIAC_RELEASE
					node1.SetAgentType("FirstAgent");
#endif
					node0.AddChild(node1);
					{
						Condition_bt_FirstTree_node2 node2 = new Condition_bt_FirstTree_node2();
						node2.SetClassNameString("Condition");
						node2.SetId(2);
#if !BEHAVIAC_RELEASE
						node2.SetAgentType("FirstAgent");
#endif
						node1.AddChild(node2);
						node1.SetHasEvents(node1.HasEvents() | node2.HasEvents());
					}
					{
						Action_bt_FirstTree_node3 node3 = new Action_bt_FirstTree_node3();
						node3.SetClassNameString("Action");
						node3.SetId(3);
#if !BEHAVIAC_RELEASE
						node3.SetAgentType("FirstAgent");
#endif
						node1.AddChild(node3);
						node1.SetHasEvents(node1.HasEvents() | node3.HasEvents());
					}
					{
						Parallel_bt_FirstTree_node4 node4 = new Parallel_bt_FirstTree_node4();
						node4.SetClassNameString("Parallel");
						node4.SetId(4);
#if !BEHAVIAC_RELEASE
						node4.SetAgentType("FirstAgent");
#endif
						node1.AddChild(node4);
						{
							Compute_bt_FirstTree_node5 node5 = new Compute_bt_FirstTree_node5();
							node5.SetClassNameString("Compute");
							node5.SetId(5);
#if !BEHAVIAC_RELEASE
							node5.SetAgentType("FirstAgent");
#endif
							node4.AddChild(node5);
							node4.SetHasEvents(node4.HasEvents() | node5.HasEvents());
						}
						{
							Action_bt_FirstTree_node6 node6 = new Action_bt_FirstTree_node6();
							node6.SetClassNameString("Action");
							node6.SetId(6);
#if !BEHAVIAC_RELEASE
							node6.SetAgentType("FirstAgent");
#endif
							node4.AddChild(node6);
							node4.SetHasEvents(node4.HasEvents() | node6.HasEvents());
						}
						node1.SetHasEvents(node1.HasEvents() | node4.HasEvents());
					}
					node0.SetHasEvents(node0.HasEvents() | node1.HasEvents());
				}
				bt.SetHasEvents(bt.HasEvents() | node0.HasEvents());
			}
			return true;
		}
	}

}
